# Generated by Django 4.1.5 on 2023-03-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GHQ12Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GHQ12_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(0, 'Better than usual'), (1, 'No more than usual'), (2, 'Rather more than usual'), (3, 'Much more than usual')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inference_engine.ghq12question')),
            ],
        ),
    ]
