# Generated by Django 4.1.5 on 2023-03-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GHQ12_response',
            new_name='GHQ12Response',
        ),
    ]
