# Generated by Django 4.1.5 on 2023-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_engine', '0003_ghq12choice_delete_ghq12response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghq12question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
