# Generated by Django 4.1.5 on 2023-03-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_engine', '0004_alter_ghq12question_question_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GHQ12Choice',
            new_name='Choice',
        ),
    ]
