# Generated by Django 4.1.5 on 2023-03-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_engine', '0005_rename_ghq12choice_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='GHChoice',
        ),
    ]
