# Generated by Django 4.1.5 on 2023-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_remove_system_rules_rule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder_diagnosis',
            name='disorder_name',
            field=models.CharField(choices=[('social_anxiety', 'Social anxiety'), ('bipolar disorder', 'Bipolar disorder'), ('ptsd', 'Post Traumatic Stress Disorder'), ('depression', 'Depression'), ('obsessive_compulsive', 'Obsessive Compulsive Disorder'), ('anti_social', 'Anti-Social personality disorder'), ('anxiety', 'Anxiety')], default='', max_length=33),
        ),
    ]
