# Generated by Django 4.1.5 on 2023-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_alter_disorder_diagnosis_disorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder_diagnosis',
            name='disorder_name',
            field=models.CharField(choices=[('Social_anxiety', 'Social anxiety'), ('Bipolar disorder', 'Bipolar disorder'), ('PTSD', 'Post Traumatic Stress Disorder'), ('Depression', 'Depression'), ('Obsessive_compulsive', 'Obsessive-Compulsive Disorder'), ('Anti_social', 'Anti-Social personality disorder'), ('Anxiety', 'Anxiety')], default='---', max_length=33),
        ),
    ]
