# Generated by Django 4.1.5 on 2023-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_alter_disorder_diagnosis_disorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder_diagnosis',
            name='disorder_name',
            field=models.CharField(max_length=255),
        ),
    ]
