# Generated by Django 4.1.5 on 2023-02-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_remove_question_question_num'),
        ('knowledge_base', '0007_alter_disorder_diagnosis_disorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_rules',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ui.choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_rules',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ui.question'),
            preserve_default=False,
        ),
    ]
