# Generated by Django 4.1.5 on 2023-03-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0007_alter_disorder_diagnosis_disorder_name'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='System_rules',
        ),
    ]
