# Generated by Django 4.1.5 on 2023-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0009_alter_disorder_diagnosis_disorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder_diagnosis',
            name='recommendation',
            field=models.TextField(null=True),
        ),
    ]
