# Generated by Django 4.1.5 on 2023-02-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0010_remove_system_rules_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder_diagnosis',
            name='recommendation',
            field=models.TextField(null=True),
        ),
    ]
