# Generated by Django 4.1.5 on 2023-01-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disorder_Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disorder_name', models.CharField(max_length=255)),
                ('disorder_desc', models.TextField()),
                ('disorder_keywords', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Psych_D_symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
                ('symptom_desc', models.TextField()),
                ('symptom_keywords', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_statement', models.TextField()),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.disorder_diagnosis')),
                ('symptom', models.ManyToManyField(to='knowledge_base.psych_d_symptoms')),
            ],
        ),
    ]
