# Generated by Django 4.1.5 on 2023-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disorder_diagnosis',
            options={'verbose_name': 'Psychological Disorder'},
        ),
        migrations.AlterModelOptions(
            name='psych_d_symptoms',
            options={'verbose_name': 'Symptoms of Disorder'},
        ),
        migrations.AlterModelOptions(
            name='system_rules',
            options={'verbose_name': 'System rule'},
        ),
        migrations.AlterField(
            model_name='disorder_diagnosis',
            name='disorder_name',
            field=models.CharField(choices=[('social_anxiety', 'Social anxiety'), ('bipolar disorder', 'bipolar disorder'), ('ptsd', 'PTSD'), ('depression', 'Depression'), ('obsessive_compulsive', 'Obsessive Compulsive'), ('anti_social', 'Anti-Social personality disorder'), ('anxiety', 'Anxiety')], default='social_anxiety', max_length=30),
        ),
    ]
