# Generated by Django 4.1.5 on 2023-02-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
