# Generated by Django 4.1.5 on 2023-02-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_rename_questions_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(null=True),
        ),
    ]
