# Generated by Django 4.1.5 on 2023-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_alter_question_question_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
