# Generated by Django 4.1.5 on 2023-02-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_alter_question_question_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_num',
        ),
    ]
