# Generated by Django 4.1.5 on 2023-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_remove_question_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
