# Generated by Django 4.1.5 on 2023-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_remove_question_id_alter_question_question_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_num',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
